version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    image: chsaiteja354/crud-mean-backend:${IMAGE_TAG:-latest}
    container_name: backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/mean_tutorials_db
    depends_on:
      - mongo

  frontend:
    image: chsaiteja354/crud-mean-frontend:${IMAGE_TAG:-latest}
    container_name: frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:

