services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: chsaiteja354/crud-mean-backend:${IMAGE_TAG:-latest}
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mean_tutorials_db
    depends_on:
      - mongo

  frontend:
    image: chsaiteja354/crud-mean-frontend:${IMAGE_TAG:-latest}
    container_name: frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mongo_data:

